# Generated by Django 5.0.7 on 2024-07-11 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='create_by',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
